import type { MenuSection, User } from "./types";
import {
  BarChart3Icon,
  BriefcaseIcon,
  Building2Icon,
  ClipboardListIcon,
  CoinsIcon,
  CreditCardIcon,
  FileTextIcon,
  HandshakeIcon,
  HomeIcon,
  // ChevronDownIcon,
  // HomeIcon,
  // LogOutIcon,
  MessageSquareIcon,
  PercentIcon,
  PiggyBankIcon,
  ScrollIcon,
  SlidersHorizontalIcon,
  StarIcon,
  UserCheckIcon,
  UserCogIcon,
  UserXIcon,
  UsersIcon,
  //   type LucideIcon,
} from "lucide-react";

export const mockUsers: User[] = [
  {
    organization: "Lendsqr",
    username: "Adedeji",
    email: "adedeji@lendsqr.com",
    phoneNumber: "08078903721",
    dateJoined: "May 15, 2020 10:00 AM",
    status: "Inactive",
  },
  {
    organization: "Irorun",
    username: "Debby Ogana",
    email: "debby2@irorun.com",
    phoneNumber: "08160780928",
    dateJoined: "Apr 30, 2020 10:00 AM",
    status: "Pending",
  },
  {
    organization: "Lendstar",
    username: "Grace Effiom",
    email: "grace@lendstar.com",
    phoneNumber: "07060780922",
    dateJoined: "Apr 30, 2020 10:00 AM",
    status: "Blacklisted",
  },
  {
    organization: "Lendsqr",
    username: "Tosin Dokunmu",
    email: "tosin@lendsqr.com",
    phoneNumber: "07003309226",
    dateJoined: "Apr 10, 2020 10:00 AM",
    status: "Pending",
  },
  {
    organization: "Lendstar",
    username: "Grace Effiom",
    email: "grace@lendstar.com",
    phoneNumber: "07060780922",
    dateJoined: "Apr 30, 2020 10:00 AM",
    status: "Active",
  },
  {
    organization: "Lendsqr",
    username: "Tosin Dokunmu",
    email: "tosin@lendsqr.com",
    phoneNumber: "08060780900",
    dateJoined: "Apr 10, 2020 10:00 AM",
    status: "Active",
  },
  {
    organization: "Lendstar",
    username: "Grace Effiom",
    email: "grace@lendstar.com",
    phoneNumber: "07060780922",
    dateJoined: "Apr 30, 2020 10:00 AM",
    status: "Blacklisted",
  },
  {
    organization: "Lendsqr",
    username: "Tosin Dokunmu",
    email: "tosin@lendsqr.com",
    phoneNumber: "08060780900",
    dateJoined: "Apr 10, 2020 10:00 AM",
    status: "Inactive",
  },
  {
    organization: "Lendstar",
    username: "Grace Effiom",
    email: "grace@lendstar.com",
    phoneNumber: "07060780922",
    dateJoined: "Apr 30, 2020 10:00 AM",
    status: "Inactive",
  },
];

export const menuSections: MenuSection[] = [
  {
    items: [
      { icon: Building2Icon, label: "Switch Organization" },
      { icon: HomeIcon, label: "Dashboard" },
    ],
  },
  {
    title: "CUSTOMERS",
    items: [
      { icon: UsersIcon, label: "Users", active: true },
      { icon: UsersIcon, label: "Guarantors", active: false },
      { icon: FileTextIcon, label: "Loans", active: false },
      { icon: HandshakeIcon, label: "Decision Models", active: false },
      { icon: PiggyBankIcon, label: "Savings", active: false },
      { icon: FileTextIcon, label: "Loan Requests", active: false },
      { icon: UserCheckIcon, label: "Whitelist", active: false },
      { icon: UserXIcon, label: "Karma", active: false },
    ],
  },
  {
    title: "BUSINESSES",
    items: [
      { icon: BriefcaseIcon, label: "Organization", active: false },
      { icon: FileTextIcon, label: "Loan Products", active: false },
      { icon: Building2Icon, label: "Savings Products", active: false },
      { icon: CoinsIcon, label: "Fees and Charges", active: false },
      { icon: CreditCardIcon, label: "Transactions", active: false },
      { icon: StarIcon, label: "Services", active: false },
      { icon: UserCogIcon, label: "Service Account", active: false },
      { icon: ScrollIcon, label: "Settlements", active: false },
      { icon: BarChart3Icon, label: "Reports", active: false },
    ],
  },
  {
    title: "SETTINGS",
    items: [
      { icon: SlidersHorizontalIcon, label: "Preferences", active: false },
      { icon: PercentIcon, label: "Fees and Pricing", active: false },
      { icon: ClipboardListIcon, label: "Audit Logs", active: false },
      { icon: MessageSquareIcon, label: "Systems Messages", active: false },
    ],
  },
];
