import type { MenuSection, User } from "./types";

export const mockUsers: User[] = [
  {
    organization: "Lendsqr",
    username: "Adedeji",
    email: "adedeji@lendsqr.com",
    phoneNumber: "08078903721",
    dateJoined: "May 15, 2020 10:00 AM",
    status: "Inactive",
    id: "1",
  },
  {
    organization: "Irorun",
    username: "Debby Ogana",
    email: "debby2@irorun.com",
    phoneNumber: "08160780928",
    dateJoined: "Apr 30, 2020 10:00 AM",
    status: "Pending",
    id: "2",
  },
  {
    organization: "Lendstar",
    username: "Grace Effiom",
    email: "grace@lendstar.com",
    phoneNumber: "07060780922",
    dateJoined: "Apr 30, 2020 10:00 AM",
    status: "Blacklisted",
    id: "3",
  },
  {
    organization: "Lendsqr",
    username: "Tosin Dokunmu",
    email: "tosin@lendsqr.com",
    phoneNumber: "07003309226",
    dateJoined: "Apr 10, 2020 10:00 AM",
    status: "Pending",
    id: "4",
  },
  {
    organization: "Lendstar",
    username: "Grace Effiom",
    email: "grace@lendstar.com",
    phoneNumber: "07060780922",
    dateJoined: "Apr 30, 2020 10:00 AM",
    status: "Active",
    id: "5",
  },
  {
    organization: "Lendsqr",
    username: "Tosin Dokunmu",
    email: "tosin@lendsqr.com",
    phoneNumber: "08060780900",
    dateJoined: "Apr 10, 2020 10:00 AM",
    status: "Active",
    id: "6",
  },
  {
    organization: "Lendstar",
    username: "Grace Effiom",
    email: "grace@lendstar.com",
    phoneNumber: "07060780922",
    dateJoined: "Apr 30, 2020 10:00 AM",
    status: "Blacklisted",
    id: "7",
  },
  {
    organization: "Lendsqr",
    username: "Tosin Dokunmu",
    email: "tosin@lendsqr.com",
    phoneNumber: "08060780900",
    dateJoined: "Apr 10, 2020 10:00 AM",
    status: "Inactive",
    id: "8",
  },
  {
    organization: "Lendstar",
    username: "Grace Effiom",
    email: "grace@lendstar.com",
    phoneNumber: "07060780922",
    dateJoined: "Apr 30, 2020 10:00 AM",
    status: "Inactive",
    id: "9",
  },
];

export const menuSections: MenuSection[] = [
  {
    items: [
      { icon: "/briefcase 1.svg", label: "Switch Organization" },
      { icon: "/home 1.svg", label: "Dashboard" },
    ],
  },
  {
    title: "CUSTOMERS",
    items: [
      { icon: "/user-friends 1.svg", label: "Users", active: true },
      { icon: "/users 1.svg", label: "Guarantors", active: false },
      { icon: "/sack 1.svg", label: "Loans", active: false },
      {
        icon: "/handshake-regular 1.svg",
        label: "Decision Models",
        active: false,
      },
      { icon: "/piggy-bank 1.svg", label: "Savings", active: false },
      { icon: "/hand-holding 1.svg", label: "Loan Requests", active: false },
      { icon: "/user-check 1.svg", label: "Whitelist", active: false },
      { icon: "/user-times 1.svg", label: "Karma", active: false },
    ],
  },
  {
    title: "BUSINESSES",
    items: [
      { icon: "/briefcase 1.svg", label: "Organization", active: false },
      { icon: "/hand-holding 1.svg", label: "Loan Products", active: false },
      {
        icon: "/np_bank_148501_000000 1.svg",
        label: "Savings Products",
        active: false,
      },
      { icon: "/coins-solid 1.svg", label: "Fees and Charges", active: false },
      { icon: "/icon.svg", label: "Transactions", active: false },
      { icon: "/galaxy 1.svg", label: "Services", active: false },
      { icon: "/user-cog 1.svg", label: "Service Account", active: false },
      { icon: "/scroll 1.svg", label: "Settlements", active: false },
      { icon: "/chart-bar 2.svg", label: "Reports", active: false },
    ],
  },
  {
    title: "SETTINGS",
    items: [
      { icon: "/sliders-h 1.svg", label: "Preferences", active: false },
      {
        icon: "/badge-percent 1.svg",
        label: "Fees and Pricing",
        active: false,
      },
      { icon: "/clipboard-list 1.svg", label: "Audit Logs", active: false },
      // {
      //   icon: "/message-square 1.svg",
      //   label: "Systems Messages",
      //   active: false,
      // },
    ],
  },
];
